# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e28f22328b05fc5816d79a8c7e7b4842d8f0a7f464b82a855632f35213d63b7dde4911f87e9b2d3ab4d434619a12f49cb6548d43677286d98f744803d13e55d

test:
  secret_key_base: 219d29d2586684238bcd47de32b840f0c8ff138257c823b42cb67894abc8cd66313f84dcc95d760f68254e3cedfaec93e0cbf34b971b5d357c32a4d53241fad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
